import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Packages from "./components/Packages";
import Footer from "./components/Footer";
import Ourservices from "./components/Ourservices";
import Contactus from "./components/Contactus";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header />
          <Hero />
        </div>
        <div>
          <Ourservices />
        </div>
        <div>
          <Packages />
        </div>
        <div>
          <Contactus/>
        </div>
        {children}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
